name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports: ['6379:6379']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Check code quality
        run: |
          pip install flake8
          flake8 app/

      - name: Build Docker image
        run: docker build -t my-flask-app .
